/**
 * Photo ledger access. data/photo-credits.json is generated by
 * scripts/photos/fetch.mjs from scripts/photos/manifest.json and is the ONLY
 * source of truth for who took each photo and under which licence. The build
 * guard (scripts/qa/photo-guard.mjs) fails when a page references an image that
 * is not in here, so every <Hero> credit resolves.
 */
import ledger from '../../data/photo-credits.json';

export interface PhotoCredit {
  /** Site path, e.g. /images/regions/jerusalem/hero.jpg */
  path: string;
  source: 'pexels' | 'unsplash' | 'commons';
  sourceId: string;
  /** Page of the photo at its source (Pexels/Unsplash photo page, Commons file page). */
  sourceUrl: string;
  title: string;
  author: string;
  authorUrl: string;
  license: string;
  licenseUrl: string;
  attributionRequired: boolean;
  alt: string;
  usedBy: string[];
  origWidth: number;
  origHeight: number;
  width: number;
  height: number;
  bytes: number;
  modified: boolean;
  downloadedAt: string;
  note?: string;
}

const LEDGER = ledger as Record<string, PhotoCredit>;

/** Human name of a source, as shown in the credit line. */
export const SOURCE_NAMES: Record<PhotoCredit['source'], string> = {
  pexels: 'Pexels',
  unsplash: 'Unsplash',
  commons: 'Wikimedia Commons',
};

/** Map any variant (-400w.avif, .webp, …) back to the ledger key (the .jpg). */
export function ledgerKey(path: string): string {
  return path
    .split('?')[0]
    .replace(/-(400|800)w(?=\.[a-z]+$)/i, '')
    .replace(/\.(avif|webp|jpeg)$/i, '.jpg');
}

/** Credit for an image path, or null when it is not in the ledger. */
export function creditFor(path: string | undefined | null): PhotoCredit | null {
  if (!path) return null;
  return LEDGER[ledgerKey(path)] ?? null;
}

/** Every ledger entry, sorted by path. */
export function allCredits(): PhotoCredit[] {
  return Object.values(LEDGER).sort((a, b) => a.path.localeCompare(b.path));
}
