/**
 * /admin/lighthouse — Lighthouse 3-run-median results viewer.
 *
 * CRITICAL (iteration-1 fix): this RSC ONLY reads `data/lighthouse-results.json`
 * via `fs.readFile`. It does NOT spawn `pnpm lhci` (or any subprocess). The CLI
 * is a separate pre-deploy step (`.github/workflows/lighthouse.yml`); the
 * route surfaces what's on disk.
 *
 * Vercel runtime forbids `child_process` from RSCs; spawning lhci would also
 * fail because Chrome is not available in the Vercel serverless runtime.
 *
 * Schema consumed (from `scripts/qa/persist-lhci.mjs`):
 *   { slug, lang, url, performance, accessibility, bestPractices, seo,
 *     thirdPartyBlockingMs, runCount, capturedAt }[]
 *
 * Plan 11 / AUD-03 / A11Y-08 — Phase 1 finalization.
 */
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Metadata } from 'next';
import type React from 'react';
import Link from 'next/link';
import { type Locale } from '@/i18n-config';

export const metadata: Metadata = {
  title: 'Lighthouse Results',
  robots: { index: false, follow: false },
};

// Re-read on every request so the dashboard reflects the latest `pnpm lhci` run
// without requiring a rebuild — mirrors the audit dashboard pattern.
export const dynamic = 'force-dynamic';

interface LighthouseEntry {
  slug: string;
  lang: 'he' | 'en';
  url?: string;
  performance: number;
  accessibility: number;
  bestPractices: number;
  seo: number;
  thirdPartyBlockingMs?: number;
  runCount?: number;
  capturedAt?: string;
}

async function loadResults(): Promise<LighthouseEntry[]> {
  const path = resolve(process.cwd(), 'data/lighthouse-results.json');
  if (!existsSync(path)) return [];
  try {
    const parsed = JSON.parse(await readFile(path, 'utf8')) as unknown;
    if (!Array.isArray(parsed)) return [];
    return parsed as LighthouseEntry[];
  } catch {
    return [];
  }
}

interface PageProps {
  params: Promise<{ locale: Locale }>;
}

/** Mobile thresholds — locked per AUD-03 / RESEARCH §1.10. */
const THRESHOLDS = {
  performance: 0.9,
  accessibility: 0.95,
  bestPractices: 0.95,
  seo: 1.0,
} as const;

function fmtScore(v: number): string {
  if (typeof v !== 'number' || Number.isNaN(v)) return '—';
  return (v * 100).toFixed(0);
}

function scoreClass(v: number, threshold: number): string {
  if (typeof v !== 'number' || Number.isNaN(v)) return '';
  return v < threshold ? 'text-[var(--color-danger)]' : '';
}

export default async function LighthousePage({
  params,
}: PageProps): Promise<React.JSX.Element> {
  const { locale } = await params;
  const results = await loadResults();

  return (
    <main id="main-content" className="mx-auto max-w-6xl p-6">
      <p>
        <Link href={`/${locale}/admin/audit`}>← Back to audit index</Link>{' '}
        ·{' '}
        <Link href={`/${locale}/admin/audit/quality-gate`}>
          Quality Gate report →
        </Link>
      </p>
      <h1 className="mt-2 text-2xl font-bold">Lighthouse Results (3-run-median)</h1>
      <p className="mt-2">
        Mobile thresholds:{' '}
        <strong>
          perf ≥{(THRESHOLDS.performance * 100).toFixed(0)} · a11y ≥
          {(THRESHOLDS.accessibility * 100).toFixed(0)} · best-practices ≥
          {(THRESHOLDS.bestPractices * 100).toFixed(0)} · SEO{' '}
          {(THRESHOLDS.seo * 100).toFixed(0)}
        </strong>
        . Source:{' '}
        <code>data/lighthouse-results.json</code> (regenerated by{' '}
        <code>pnpm lhci</code>).
      </p>
      {results.length === 0 ? (
        <div className="mt-4 rounded border border-dashed p-4">
          <p>
            <strong>No Lighthouse runs captured yet.</strong>
          </p>
          <p className="mt-2">
            Trigger a run via <code>pnpm build &amp;&amp; pnpm lhci</code> (local
            — requires Chrome installed). CI runs automatically on every PR + push
            to main via <code>.github/workflows/lighthouse.yml</code>.
          </p>
          <p className="mt-2 text-sm">
            AUD-013 and AUD-034 audit rules currently emit
            <code> info: deferred</code> entries; they will fire as{' '}
            <code>severity: major</code> once this file is populated and any score
            falls below threshold.
          </p>
        </div>
      ) : (
        <>
          <table className="mt-4 w-full border-collapse">
            <thead>
              <tr className="border-b">
                <th className="p-2 text-start">URL / Slug</th>
                <th className="p-2 text-start">Lang</th>
                <th className="p-2 text-start">Perf</th>
                <th className="p-2 text-start">A11Y</th>
                <th className="p-2 text-start">Best Practices</th>
                <th className="p-2 text-start">SEO</th>
                <th className="p-2 text-start">TBT (ms)</th>
                <th className="p-2 text-start">Runs</th>
              </tr>
            </thead>
            <tbody>
              {results.map((r, i) => (
                <tr key={`${r.slug || 'root'}-${r.lang}-${i}`} className="border-b">
                  <td className="p-2">
                    <code>{r.slug || '(root)'}</code>
                    {r.url ? (
                      <div className="text-xs text-[var(--color-muted)]">{r.url}</div>
                    ) : null}
                  </td>
                  <td className="p-2">{r.lang}</td>
                  <td className={`p-2 ${scoreClass(r.performance, THRESHOLDS.performance)}`}>
                    {fmtScore(r.performance)}
                  </td>
                  <td
                    className={`p-2 ${scoreClass(r.accessibility, THRESHOLDS.accessibility)}`}
                  >
                    {fmtScore(r.accessibility)}
                  </td>
                  <td
                    className={`p-2 ${scoreClass(r.bestPractices, THRESHOLDS.bestPractices)}`}
                  >
                    {fmtScore(r.bestPractices)}
                  </td>
                  <td className={`p-2 ${scoreClass(r.seo, THRESHOLDS.seo)}`}>
                    {fmtScore(r.seo)}
                  </td>
                  <td
                    className={`p-2 ${
                      typeof r.thirdPartyBlockingMs === 'number' &&
                      r.thirdPartyBlockingMs > 250
                        ? 'text-[var(--color-danger)]'
                        : ''
                    }`}
                  >
                    {typeof r.thirdPartyBlockingMs === 'number'
                      ? r.thirdPartyBlockingMs
                      : '—'}
                  </td>
                  <td className="p-2">{r.runCount ?? '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {results[0]?.capturedAt ? (
            <p className="mt-2 text-xs text-[var(--color-muted)]">
              Captured: {results[0].capturedAt}
            </p>
          ) : null}
        </>
      )}
    </main>
  );
}
