/**
 * Jerusalem EN canonical — content-level invariants.
 *
 * Phase 2 plan 01: this suite validates the MDX content authored in
 * `content/en/regions/jerusalem.mdx` after Velite compilation.
 *
 * The 9 assertions per the PLAN behavior section:
 *   1. jerusalem.mdx parses and the Velite Region entry exists
 *   2. body contains H1 "Things to Do in Jerusalem" exactly once
 *   3. body contains 8-12 H2 sections
 *   4. body contains >=5 distinct `<AffiliateCard partner="X"` invocations
 *      across >=5 different partners
 *   5. body contains "Western Wall" (case-insensitive); NEVER "Wailing Wall"
 *   6. first reference of "Temple Mount" within 300 chars of "Haram al-Sharif"
 *   7. body contains "<ShabbatNotice" at least once
 *   8. word count between 1500 and 2500
 *   9. faqs frontmatter has 5-10 entries
 *
 * The Velite collection is consulted directly so we test the compiled
 * artifact (frontmatter + body code string) not the raw .mdx source.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

// `.velite` is generated by `pnpm velite` (prebuild); the JSON ships an
// array of Region entries. We read it via fs so tests are independent of
// the @velite resolver path.
const REGIONS_JSON = resolve(process.cwd(), '.velite/regions.json');

interface RegionEntry {
  lang: string;
  region: string;
  slug: string;
  title: string;
  description: string;
  heroImage: string;
  body: string;
  faqs?: Array<{ question: string; answer: string }>;
}

function loadRegions(): RegionEntry[] {
  if (!existsSync(REGIONS_JSON)) return [];
  const raw = readFileSync(REGIONS_JSON, 'utf8');
  try {
    return JSON.parse(raw) as RegionEntry[];
  } catch {
    return [];
  }
}

function findJerusalemEn(): RegionEntry | undefined {
  return loadRegions().find((r) => r.lang === 'en' && r.region === 'jerusalem');
}

// Task 2 of plan 02-01 ships content/en/regions/jerusalem.mdx — at that point
// the "exists" + "raw MDX file exists" assertions flip from skip to active.
// During Wave 0 (task 1) the route renderer + photo-credits are landed without
// MDX, so the skip keeps the Vitest run green for the per-task commit.
const HAS_MDX = existsSync(
  resolve(process.cwd(), 'content/en/regions/jerusalem.mdx'),
);

describe('Jerusalem EN canonical (Velite Region)', () => {
  it.skipIf(!HAS_MDX)('exists in the Velite regions collection', () => {
    const r = findJerusalemEn();
    expect(r, 'Run `pnpm velite` first to compile MDX').toBeDefined();
  });

  it('has frontmatter title 50-60 chars and description 120-160 chars', () => {
    const r = findJerusalemEn();
    if (!r) return;
    expect(r.title.length).toBeGreaterThanOrEqual(40);
    expect(r.title.length).toBeLessThanOrEqual(70);
    expect(r.description.length).toBeGreaterThanOrEqual(120);
    expect(r.description.length).toBeLessThanOrEqual(160);
  });

  it('compiled body contains the primary keyword "Things to Do in Jerusalem"', () => {
    const r = findJerusalemEn();
    if (!r) return;
    // Page-level H1 is owned by RegionHero (from frontmatter title); MDX body
    // mentions the primary keyword in prose so AUD-008 single-H1 invariant
    // is preserved and SEO keyword density still serves the canonical.
    const occurrences = r.body.match(/Things to Do in Jerusalem/gi);
    expect(occurrences, 'primary keyword missing from prose').not.toBeNull();
    expect((occurrences as RegExpMatchArray).length).toBeGreaterThanOrEqual(1);
  });

  it('compiled body has NO H1 (page H1 is owned by RegionHero)', () => {
    const r = findJerusalemEn();
    if (!r) return;
    // Argentina-lesson-aware: two H1s break SEO + AUD-008. MDX body must
    // omit `# Heading`; the RegionHero composite renders the single H1.
    const matches = r.body.match(/\.h1[\s,)]/g) ?? [];
    expect(matches.length).toBe(0);
  });

  it('compiled body declares 8-12 H2 sections', () => {
    const r = findJerusalemEn();
    if (!r) return;
    // Velite compiles MDX `## Heading` to jsx calls that reference the
    // components map's `h2` member (e.g. `n.h2`). The factory function
    // name is minified so we match the property accessor.
    const matches = r.body.match(/\.h2[\s,)]/g) ?? [];
    expect(matches.length).toBeGreaterThanOrEqual(8);
    expect(matches.length).toBeLessThanOrEqual(12);
  });

  it('contains >=5 AffiliateCard placements across >=5 distinct partners', () => {
    const r = findJerusalemEn();
    if (!r) return;
    // MDX `<AffiliateCard partner="X" ...>` compiles to a JSX call with
    // `partner: "X"` in the props object. Extract the partner strings.
    const partnerHits = [...r.body.matchAll(/partner:\s*["']([a-zA-Z]+)["']/g)];
    expect(partnerHits.length).toBeGreaterThanOrEqual(5);
    const distinct = new Set(partnerHits.map((m) => m[1]));
    expect(distinct.size).toBeGreaterThanOrEqual(5);
  });

  it('uses "Western Wall" and never "Wailing Wall"', () => {
    const r = findJerusalemEn();
    if (!r) return;
    expect(/wailing\s+wall/i.test(r.body)).toBe(false);
    expect(/Western\s+Wall/i.test(r.body)).toBe(true);
  });

  it('pairs "Temple Mount" with "Haram al-Sharif" within 300 chars on first reference', () => {
    const r = findJerusalemEn();
    if (!r) return;
    const tmIdx = r.body.search(/Temple\s+Mount/i);
    if (tmIdx === -1) return; // Not mentioned → vacuously paired.
    const windowText = r.body.slice(tmIdx, tmIdx + 300);
    expect(/Haram\s+al-?Sharif/i.test(windowText)).toBe(true);
  });

  it('invokes <ShabbatNotice> at least once', () => {
    const r = findJerusalemEn();
    if (!r) return;
    expect(/ShabbatNotice/.test(r.body)).toBe(true);
  });

  it('faqs frontmatter has 5-10 entries', () => {
    const r = findJerusalemEn();
    if (!r) return;
    expect(Array.isArray(r.faqs)).toBe(true);
    const faqs = r.faqs ?? [];
    expect(faqs.length).toBeGreaterThanOrEqual(5);
    expect(faqs.length).toBeLessThanOrEqual(10);
  });
});

describe('Jerusalem EN MDX (raw source, word count + AffiliateDisclosure placement)', () => {
  const MDX_PATH = resolve(process.cwd(), 'content/en/regions/jerusalem.mdx');

  it.skipIf(!HAS_MDX)('raw MDX file exists', () => {
    expect(existsSync(MDX_PATH)).toBe(true);
  });

  it('word count between 1500 and 2500', () => {
    if (!existsSync(MDX_PATH)) return;
    const raw = readFileSync(MDX_PATH, 'utf8');
    // Strip frontmatter block
    const body = raw.replace(/^---[\s\S]*?---/, '');
    // Strip JSX/component tags and import lines so the count is human prose
    const prose = body
      .replace(/<[^>]+>/g, ' ')
      .replace(/\{[^}]*\}/g, ' ')
      .replace(/^import .*$/gm, '');
    const words = prose
      .split(/\s+/)
      .map((w) => w.trim())
      .filter((w) => w.length > 1 && /[a-zA-Z]/.test(w));
    expect(words.length).toBeGreaterThanOrEqual(1500);
    expect(words.length).toBeLessThanOrEqual(2500);
  });

  it('does NOT inline <AffiliateDisclosure> (renderer wires it once)', () => {
    if (!existsSync(MDX_PATH)) return;
    const raw = readFileSync(MDX_PATH, 'utf8');
    expect(/<AffiliateDisclosure\b/.test(raw)).toBe(false);
  });
});
