import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

// Representative of every template type + each interactive tool.
const ROUTES = [
  '/',
  '/fr/',
  '/de/',
  '/fr/plan-your-trip',
  '/de/plan-your-trip',
  '/jerusalem',
  '/jerusalem/western-wall',
  '/itineraries',
  '/itineraries/7-days-in-israel',
  '/itineraries/3-days-in-jerusalem',
  '/itineraries/2-days-in-tel-aviv',
  '/first-time-in-israel',
  '/visa-information',
  '/plan-your-trip',
  '/best-holy-land-tours',
  '/fr/first-time-in-israel',
  '/fr/visa-information',
  '/fr/best-time-to-visit-israel',
  '/fr/transportation',
  '/fr/israel-cost-budget',
  '/fr/day-trips-from-jerusalem',
  '/fr/day-trips-from-tel-aviv',
  '/fr/is-israel-safe',
  '/fr/shabbat-guide',
  '/fr/best-tours-in-israel',
  '/fr/border-crossings',
  '/fr/car-rental-israel',
  '/de/first-time-in-israel',
  '/de/visa-information',
  '/de/best-time-to-visit-israel',
  '/de/transportation',
  '/de/israel-cost-budget',
  '/de/day-trips-from-jerusalem',
  '/de/day-trips-from-tel-aviv',
  '/de/is-israel-safe',
  '/de/shabbat-guide',
  '/de/best-tours-in-israel',
  '/de/border-crossings',
  '/de/car-rental-israel',
  '/fr/bar-bat-mitzvah-israel',
  '/fr/hiking-in-israel',
  '/fr/kosher-food-guide',
  '/de/bar-bat-mitzvah-israel',
  '/de/hiking-in-israel',
  '/de/kosher-food-guide',
  '/fr/water-hiking-israel',
  '/fr/israel-adventure-sports',
  '/fr/ben-gurion-airport-guide',
  '/de/water-hiking-israel',
  '/de/israel-adventure-sports',
  '/de/ben-gurion-airport-guide',
  '/fr/israel-for-seniors',
  '/fr/whats-open-on-shabbat',
  '/fr/holy-sites-dress-code-etiquette',
  '/de/israel-for-seniors',
  '/de/whats-open-on-shabbat',
  '/de/holy-sites-dress-code-etiquette',
  '/fr/israel-5-vs-7-vs-10-days',
  '/fr/best-holy-land-tours',
  '/fr/dead-sea-guide',
  '/fr/israel-travel-insurance',
  '/de/israel-5-vs-7-vs-10-days',
  '/de/best-holy-land-tours',
  '/de/dead-sea-guide',
  '/de/israel-travel-insurance',
  '/fr/christian-pilgrimage-holy-land',
  '/de/christian-pilgrimage-holy-land',
  '/fr/israel-national-parks-pass',
  '/de/israel-national-parks-pass',
  '/fr/driving-in-israel',
  '/de/driving-in-israel',
  '/build-your-trip',
  '/israel-map',
  '/israel-trip-cost-calculator',
  '/israel-tipping-currency',
  '/israel-packing-list',
  '/israel-weather-packing',
  '/which-israel-region-quiz',
  '/israel-distance-calculator',
  '/israel-how-many-days',
  '/best-things-to-do-in-israel',
  '/where-to-stay/jerusalem',
  '/where-to-stay/tel-aviv',
  '/where-to-stay/dead-sea',
  '/transport/jerusalem-to-dead-sea',
  '/transport/tel-aviv-to-haifa',
  '/masada-tours-compared',
  '/galilee-tours-compared',
  '/petra-tours-compared',
  '/tel-aviv-tours-compared',
  '/eilat-tours-compared',
  '/cruise-shore-excursions-israel',
  '/israel-accommodation-guide',
  '/israel-travel-apps',
  '/jewish-heritage-israel',
  '/bar-bat-mitzvah-israel',
  '/israel-food-tours-cooking-classes',
  '/driving-in-israel',
  '/israel-national-parks-pass',
  '/israel-for-seniors',
  '/israel-adventure-sports',
  '/ben-gurion-airport-guide',
  '/israel-restaurant-finder',
  '/israel-travel-insurance',
  '/car-rental-israel',
  '/water-hiking-israel',
  '/akko-acre-guide',
  '/safed-tzfat-guide',
  '/nazareth-travel-guide',
  '/dead-sea-guide',
  '/israel-holiday-planner',
  '/israel-visa-eta-checker',
  '/israel-parks-pass-calculator',
  '/israel-shabbat-countdown',
  '/search',
  '/404',
];

for (const route of ROUTES) {
  test(`no WCAG 2A/2AA violations on ${route}`, async ({ page }) => {
    await page.goto(route, { waitUntil: 'load' });
    const results = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .analyze();
    // Surface a readable summary if anything regresses.
    const summary = results.violations.map(
      (v) => `${v.impact} · ${v.id} (${v.nodes.length}) — ${v.help}`
    );
    expect(summary, summary.join('\n')).toEqual([]);
  });
}
